footprint: [[-0.145,-0.08],[0.0,-0.08],[0.0,0.08],[-0.145,0.08]]
footprint_padding: 0.01
robot_base_frame: base_link

transform_tolerance: 0.2 # do tre 
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 3
 raytrace_range: 3.5
 inflation_radius: 0.2
 track_unknown_space: false
 combination_method: 1

 observation_sources: laser
 laser: {data_type: LaserScan, topic: scan, marking: true, clearing: true}
 observation_sources: vision_scan    

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "map"
