frequency: 30.0
two_d_mode: true
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom


odom0: /wheel_odom
odom0_config: [true,  true,  false,   # X, Y từ encoder
               false, false, false,   # Không lấy roll/pitch/yaw tuyệt đối từ wheel odom
               true,  false, false,   # Vx từ encoder
               false, false, true,    # yaw rate từ encoder (nếu có)
               false, false, false]
odom0_differential: false            # Wheel odom là tuyệt đối


imu0: /imu/data
imu0_config: [false, false, false,   # IMU không cung cấp vị trí
              false, false,  true,   # Lấy roll/pitch, bỏ yaw tuyệt đối (MPU6050 không có heading tin cậy)
              false, false, false,   # Không dùng linear velocity từ IMU
              false, false,  true,    # Gyro 3 trục
              false, false, false]
imu0_differential: false             # Dùng roll/pitch tuyệt đối, gyro trực tiếp
